import { useState } from 'react';
import { StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import i18n from '@/utils/i18n';
import { useTheme } from '@/contexts/ThemeContext';
import type { SurveyAnswers } from '@/contexts/AuthContext';
import type { UserSurvey } from '@/services/api/user';

export function SurveyForm({ onSubmit }: { onSubmit: (answers: SurveyAnswers) => void }) {
  const { colors, typography } = useTheme(); const [acquisitionSource, setAcquisition] = useState<SurveyAnswers['acquisitionSource']>(); const [practice, setPractice] = useState<SurveyAnswers['practice']>(); const [newsletterOptIn, setNewsletter] = useState(false);
  const choices = <T extends string>(prefix: string, values: [T, string][], selected: T | undefined, set: (value: T | undefined) => void) => <View style={styles.chips}>{values.map(([key, label]) => <TouchableOpacity accessibilityRole="button" key={key} testID={`survey-${prefix}-${key}`} onPress={() => set(selected === key ? undefined : key)} style={[styles.chip, { borderColor: selected === key ? colors.accent : colors.border, backgroundColor: selected === key ? colors.accent : colors.surface }]}><Text style={{ color: selected === key ? '#fff' : colors.textPrimary }}>{label}</Text></TouchableOpacity>)}</View>;
  const acquisitionValues: [NonNullable<UserSurvey['acquisitionSource']>, string][] = [['app_store', i18n.t('survey.appStore')], ['google_search', i18n.t('survey.google')], ['instagram', i18n.t('survey.instagram')], ['tiktok', i18n.t('survey.tiktok')], ['word_of_mouth', i18n.t('survey.wordOfMouth')], ['other', i18n.t('survey.other')]];
  const practiceValues: [NonNullable<UserSurvey['practice']>, string][] = [['hiker', i18n.t('survey.hiker')], ['trail_runner', i18n.t('survey.trail')], ['paraglider', i18n.t('survey.paraglider')], ['photographer', i18n.t('survey.photographer')], ['mountaineer', i18n.t('survey.alpinist')], ['other', i18n.t('survey.other')]];
  return <View style={styles.container}><Text style={[styles.title, { color: colors.textPrimary, fontFamily: typography.fontFamily.bold }]}>{i18n.t('survey.title')}</Text><Text style={{ color: colors.textSecondary }}>{i18n.t('survey.subtitle')}</Text><Text style={[styles.question, { color: colors.textPrimary }]}>{i18n.t('survey.discovery')}</Text>{choices('acquisition', acquisitionValues, acquisitionSource, setAcquisition)}<Text style={[styles.question, { color: colors.textPrimary }]}>{i18n.t('survey.practice')}</Text>{choices('practice', practiceValues, practice, setPractice)}<TouchableOpacity accessibilityRole="checkbox" accessibilityState={{ checked: newsletterOptIn }} testID="survey-newsletter" onPress={() => setNewsletter(!newsletterOptIn)} style={styles.newsletter}><View style={[styles.checkbox, { borderColor: colors.textSecondary, backgroundColor: newsletterOptIn ? colors.accent : colors.surface }]}>{newsletterOptIn ? <Text style={{ color: '#fff' }}>✓</Text> : null}</View><Text style={{ color: colors.textSecondary }}>{i18n.t('survey.newsletter')}</Text></TouchableOpacity><TouchableOpacity accessibilityRole="button" testID="survey-submit" onPress={() => onSubmit({ acquisitionSource, practice, newsletterOptIn })} style={[styles.submit, { backgroundColor: colors.accent }]}><Text style={{ color: '#fff' }}>{acquisitionSource || practice || newsletterOptIn ? i18n.t('survey.finish') : i18n.t('survey.continue')}</Text></TouchableOpacity></View>;
}
const styles = StyleSheet.create({ container: { gap: 12 }, title: { fontSize: 27 }, question: { fontSize: 15, fontWeight: '600', marginTop: 14 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 }, chip: { minHeight: 44, paddingHorizontal: 15, justifyContent: 'center', borderRadius: 999, borderWidth: 1 }, newsletter: { flexDirection: 'row', gap: 8, alignItems: 'center', marginTop: 10 }, checkbox: { width: 18, height: 18, borderWidth: 1.5, borderRadius: 5, alignItems: 'center', justifyContent: 'center' }, submit: { height: 50, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginTop: 10 } });
